{% set version = "1.0.0" %}

package:
  name: feature_annotation
  version: "{{ version }}"

build:
  script: bash build.sh

source:
  url: https://github.com/debjit20504/feature_annotation/archive/refs/tags/v{{ version }}.tar.gz 
  sha256 : a004e24fc0504cea5202cc17bea6f90b76390fb22e605fca3c05f68352689bcd

requirements:
  host:
    - bash
  run:
    - python >=3
    - conda
    - requests
    - pandas
    - bs4
test:
  commands:
    - feature_annotation -h

about:
  home: https://github.com/debjit20504/feature_annotation
  license: MIT
  summary: feature annotation is a command-line tool that provides detailed information about biological
    entities identified by unique identifiers (IDs). Given a text file containing a list
    of IDs, which can be from COG, BIGG, or EC databases, the tool fetches and presents
    relevant information about each ID.