package:
  name: feature_annotation
  version: 1.0.0

source:
  path: ..

build:
  script: ./build.sh

requirements:
  build:
    - bash
  run:
    - python
    - conda
    - requests
    - pandas
    - bs4

about:
  home: https://github.com/debjit20504/feature_annotation
  license: MIT
  summary: feature annotation is a command-line tool that provides detailed information about biological
    entities identified by unique identifiers (IDs). Given a text file containing a list
    of IDs, which can be from COG, BIGG, or EC databases, the tool fetches and presents
    relevant information about each ID.
